#ifndef TOKENTYPES_H_INCLUDED
#define TOKENTYPES_H_INCLUDED

/**
* \brief Different TokenTypes available
*/
enum TokenTypes {
                    // General tokens
                    TOK_IF=0, TOK_SWITCH, TOK_SELECT, TOK_ELSE, TOK_ELSEIF, TOK_THEN, TOK_FOR, TOK_WHILE, TOK_DO, TOK_FUNCDECL,
                    TOK_FUNC, TOK_PREPROCESS, TOK_VARDECL, TOK_VAR, TOK_LITERAL, TOK_CLASS, TOK_ENDCLASS,
                    TOK_PREDEFINEDVAR, TOK_RETURN, TOK_CONTINUE, TOK_DEFAULT, TOK_GEN_EXIT, TOK_CASE, TOK_STATIC, TOK_VOLATILE,
                    TOK_CONST, TOK_WITH, TOK_ENDWITH, TOK_ENDIF, TOK_ENDSELECT, TOK_ENDSWITCH, TOK_TO, TOK_STEP,
                    TOK_NULL, TOK_UNTIL, TOK_NEXT, TOK_WEND, TOK_BRACKET_OPEN, TOK_BRACKET_CLOSE, TOK_ENDFUNC, TOK_UNKNOWN,
                    TOK_ENUM,TOK_SYNCHRONIZED , TOK_BYREF,

                    // More speicifc tokens
                    TOK_OP_NOT, TOK_OP_MOD, TOK_OP_ADD, TOK_OP_SUB, TOK_OP_MUL, TOK_OP_DIV, TOK_OP_SHL, TOK_OP_SHR,
                    TOK_OP_JOIN, TOK_OP_POW, TOK_OP_INC, TOK_OP_DEC, TOK_ASSIGN, TOK_DEFAULT_ASSIGN, TOK_ASSIGN_MOD, TOK_ASSIGN_ADD, TOK_ASSIGN_SUB,
                    TOK_ASSIGN_MUL, TOK_ASSIGN_DIV, TOK_ASSIGN_SHL, TOK_ASSIGN_SHR, TOK_ASSIGN_JOIN, TOK_ASSIGN_POW,
                    TOK_COMP_EQCASE, TOK_COMP_EQINCASE, TOK_COMP_LOWEREQ, TOK_COMP_GREATEREQ, TOK_COMP_NOTEQ, TOK_COMP_LESS,
                    TOK_COMP_GREATER, TOK_LOGIC_AND, TOK_LOGIC_OR, TOK_PUNCT_COMMENT, TOK_PUNCT_DOT,
                    TOK_PUNCT_COMMA, TOK_PUNCT_QST, TOK_PUNCT_DOUBLEDOT, TOK_NUMBER_HEX, TOK_NUMBER_DEC, TOK_NUMBER_BIN,
                    TOK_EXIT_LOOP, TOK_TRUE, TOK_FALSE, TOK_BRACKET_ROUND_OPEN, TOK_NEW,
                    TOK_BRACKET_ANGLE_OPEN, TOK_BRACKET_ARRAY_OPEN,TOK_BRACKET_ROUND_CLOSE, TOK_PUNCT_NOT,
                    TOK_BRACKET_ANGLE_CLOSE, TOK_BRACKET_ARRAY_CLOSE, TOK_NEWLINE, TOK_BRACKET_ARRAY_ACCESS, TOK_BRACKET_ARRAY_CREATION,TOK_BRACKET_ARRAY_APPEND,
                    TOK_JMP_LABEL,

                    TOK_END, TOK_ROOT, TOK_STANDARD_FUNC, TOK_COMMA_VAR};
#endif // TOKENTYPES_H_INCLUDED

